# https://www.mkdocs.org/user-guide/configuration/
# https://www.mkdocs.org/user-guide/writing-your-docs/
# https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/writing-your-docs/
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/styling-your-docs/
# https://example-mkdocs-basic.readthedocs.io/en/latest/
# https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml
# https://squidfunk.github.io/mkdocs-material/creating-your-site/
# mkdocs.yml

site_name: Catesta - a PowerShell module and vault project generator.
# site_url:
repo_url: https://github.com/techthoughts2/Catesta
# repo_name:
# edit_uri: edit/main/docs/
# edit_uri_template:
site_description: Catesta is a PowerShell and vault module project generator. It uses templates to rapidly scaffold test and build integration for a variety of CI/CD platforms. # meta tag to the generated HTML header
site_author: Jake Morrison # meta tag to the generated HTML header
copyright: "Catesta is licensed under the <a href='https://github.com/techthoughts2/Catesta/blob/main/LICENSE'>MIT license"
# remote_branch:
# remote_name:
# docs_dir: docs
# site_dir:
# extra_css:
# extra_javascript:
markdown_extensions:
  # Python Markdown
  - admonition
  - toc:
      permalink: true
  # code highlighting
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# extra_templates:
# extra:
# theme: readthedocs
theme:
  name: material
  language: en
  # custom_dir: overrides
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.path
  favicon: assets/Catesta_favicon-32x32.png
  icon:
    repo: fontawesome/brands/github
  # font:
  #   text: Work Sans
  logo: assets/CatestaIcon.png
  # palette:
  #   primary: teal
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# theme:
#     name: readthedocs
#     locale: en
    # custom_dir: my_theme_customizations/
    # static_templates:
    #     - sitemap.html
    # include_sidebar: true
nav:
  - Overview: index.md
  - Usage:
    - Catesta Basics: Catesta-Basics.md
    - Catesta Advanced: Catesta-Advanced.md
    - Module Schema: Catesta-ModuleSchema.md
    - Vault Schema: Catesta-VaultSchema.md
  - Functions:
    - New-ModuleProject: New-ModuleProject.md
    - New-VaultProject: New-VaultProject.md
  - Detailed Integrations:
    - AppVeyor: catesta_cicd/Catesta-AppVeyor.md
    - CodeBuild: catesta_cicd/Catesta-AWS.md
    - Azure: catesta_cicd/Catesta-Azure.md
    - GitHub Actions: catesta_cicd/Catesta-GHActions.md
    - Bitbucket Pipelines: catesta_cicd/Catesta-Bitbucket.md
    - GitLab CICD Pipelines: catesta_cicd/Catesta-GitLab.md
    - Vault Project: Catesta-Vault-Extension.md
  - FAQ: Catesta-FAQ.md
  - Change Log: CHANGELOG.md
